minctoolkit_variant:
  - noblas
#  - legacy
minctoolkit_visual:
  - novisual
#  - full
hdf5: 1.10.6 
# =nompi_h6a2412b_1114
libnetcdf: 4.8.1
# = nompi_hcd642e3_100
pin_run_as_build:
    libnetcdf:
      max_pin: x.x
    hdf5:
      max_pin: x.x.x
      min_pin: x.x.x
c_compiler_version: # [unix]
  - 12.2.0 # [linux]
cxx_compiler_version: 
  - 12.2.0 # [linux]
